language: java
sudo: false

script:
  - mvn -Dsurefire.rerunFailingTestsCount=10 test
  - mvn checkstyle:check

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - ./deploy.sh


jdk:
  - openjdk8

matrix:
  allow_failures:
    - os: osx

os:
  - linux
  # - osx

cache:
  directories:
    - "$HOME/.m2"

env:
  global:
  - secure: ckZ/ntTa9ktkprRr72Rx4kkPVUD1CDEXLHyfLTAbVhhySkn0RZFyH6LUId7nKlqZRv3FkpTv3y14cCVzY9dGTw131gamGTiJqbcsJzadBtClVK00FZXlfaX198DQQTcz2/QGcjeojJCwqWN/o0RCETeShg2zJMpddKoc5p3nO+VvYQyr/jJW3wrjuNbK55Smh6n8Uszm8AZNZLPRR+y6gMERLLsWwxJy/Py3YxN9Ky70SWtXdS2PB27FfYJCw/zmm6aVEBBI7UB1Ee0C6cufMdhKmr7LB5f7r23mBA85GqdOjD5rwGQEr7vxXt3XhwTjEMEgAvHDXYzYdi5R29UNozk0IY3uM6aEydCuo0mZFx1iYT1OwwDatBpL0SyKKCmPTXm5UwX7UeK0fo6xW3GmtwJ/5KrfIZUA/Tx7tM4G1hdgZMr+7Snby5y7tODCuGgI57me2PaEqlkMi1n7lvjeoWt5QFKjgjzlk17yQj0Pgo0DkFRMwJFNiG6hBl52g6Gt4uNKzirIpJXj3c2OR+BRhIOPtAmyWXJmJMGKg1+RpzuNiBqSEXs7uSHaql1zzUvaFKgLbirtAjPHEjDyvnwTkaGRofB4Y5HGrRE8SgZx1yjP1dYv98MNYFfghR/tabcvbPJ2UyQ71r4nKt+oi/bjGTmpLLM/jYVRbstRNtBiwQE=
  - secure: 17eycWETyUp0uLhFGHpQKShLCfbyh/ahJ2aYDjDZ7PJD+YSNf8aJqfrk5yuWnJL+cJUi++e3MpOg5hoyeJkeFjMaDYPN12mDq7Uag8dcV33xIg0uRVt/wVLey6oSkYg2a+A8tuK2mfYXWxo6MTqPpBAuARiVAl8L2PaVcFk9wRz994q0MXUgFltsMrtjmQCLI4Cr9zNWo9WAFLcq8cbwVi3YsVI39Dbi6OR516Y82ZEA0bXEEgeIc9pEGhZPjj5+ni5vAxpvt1Y1n9bADdTqWnwoRwd9l0VycwTv0P66tdTDuQ0+qM/tOfOCj49jSPjr5G4xu37D/74A1FDxwx2I5K/sCjCiHQxK4NnPICmqFuTYduk0q4KSvQcYtExa3M4c+nNjZ7hLUECmq8Gzwy8nRR6b4LMn+WSKNUEX4L/CoLxmVn82srvhnPqSAZ/9tD95TLPD1OFixJhutcFHzsLRTyp+fudLPSSaMQghNO76QGa31H1bb2pNfKk5MuzArzhhQfmfee86fJYAuB2JzobGREcl4eN+7G4yyLixktE9kvBAFBWhN2MxrWB0f3uX5Sex1cDHHK2QxAuI9x/naIHtbBNsxy753sFApGZh6UF4VqpTOAbupWOJ05AkPMpq9GeTA0Y/YZDsm/5WASqrPsOvkhWcdejIHdinmMYGIAnfaCg=
